import { Geist, Geist_Mono } from "next/font/google";
import { Header, Providers } from "@/components";

import "./globals.css";
import {
  ClerkProvider,
  SignedOut,
  SignInButton,
  SignUpButton,
} from "@clerk/nextjs";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <body className="bg-white dark:bg-[#191919] text-[#37352f] dark:text-[#ffffffcf]">
          <Providers>
            <Header />

            {children}
          </Providers>
        </body>
      </html>
    </ClerkProvider>
  );
}
