import { ClerkProvider } from "@clerk/nextjs";
import "./globals.css";
import { Header, Providers } from "../components";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <body className="bg-white dark:bg-[#191919] text-[#37352f] dark:text-[#ffffffcf]">
          <Providers>
            <Header />
            {children}
          </Providers>
        </body>
      </html>
    </ClerkProvider>
  );
}
